### ISSUE TITLE
Issue seeing passwords

### ISSUE THREAD

**Issue by jpoa** [tildaslash/RatticWeb#229]
Greetings,

I am having a strange issue with some users. On a manager account I can see all the passwords clicking the eye button (which calls the function showPass()), all works well, including the call to api/v1/cred, etc.

Doing the same with a user account returns a 404 (which means that clicking the eye button does nothing). However, if the user goes to edit, he can see the password.

Cheers!

**Comment by rayvenshire** [comment]
I've encountered this issue for Rattic v1.3 on Ubuntu 14.04 LTS x64 running Apache2 2.4.7-1ubuntu4.4.

User sees "Fetching password..." but does not ever see password. This happens for all keys for which they are a member of a viewer group. This does not happen for keys in which they are the owning group. It also does not happen to staff members. This happens both in firefox and chrome.

First error in console showed "SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data"

Followed @kris7778's suggestion above to upgrade pip modules. Ending up installing "libldap2-dev", as it was not installed on this machine. After restarting apache2, "Fetching password" error still manifested. Console now showed this error: "Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src https://rattic-dev.domain.com")." Another user noted that clicking on the reveal button resulted in "GET https://rattic-dev.domain.com/api/v1/cred/10/ 401 (UNAUTHORIZED)".

Dug into the "Content Security Policy", which was ultimately seemingly mitigated by this command "pip install requests[security]". However, to get that to complete, I had to install "libffi-dev" and "libssl-dev" packages. A subsequent restart of apache2 still showed the same 401 error. 

I then changed logging to DEBUG for both apache2 and in local.cfg, but do not see the 401 in the apache2 error log.

I have the pip modules and versions (taken from pip freeze) from before anything was done, after the installation "libldap2-dev" and then again after the installation of "libffi-dev" and "libssl-dev" -- please let me know if you want those attached.

**Comment by rayvenshire** [comment]
This bug is currently replicate-able on the demo site. For ease, I've already set it up -- log in as "test" with "password" and attempt to view "TEST". You'll note that when you load the page, the blurred text is "Fetching Password...". Mousing over it directly or clicking the unmask button both will fail with a 401.

**Comment by smarthall** [comment]
Reopening now that we have a repeatable test case

**Comment by refj** [comment]
Just wanted confirm that we are seeing the same issue with a user who is neither a member of a the owner nor staff group using RatticDB 1.3 with latest requirements installed.

**Comment by refj** [comment]
Just tested this:

1. Applied patch manually.
diff api.py api.py.old 
27c27
<         if not bundle.obj.is_visible_by(bundle.request.user):
---
>         if not bundle.obj.is_owned_by(bundle.request.user):
2. Restarted web server.
3. Removed myself from staff and owner group and added my user to the viewer group in AD.
4. Viewed the password entry and the password shows.

Thanks smarthall.

**Comment by rayvenshire** [comment]
Also tested:

1. Applied patch manually
2. Restarted web server
3. Added new key with other user in viewer group
4. User confirmed they could view

Thanks

**Comment by smarthall** [comment]
Will be fixed in v1.3.1

**Comment by priya124** [comment]
I cannot open ratticdb on browser after installed in ubuntu 12.04
i set hostname as ratticdb and permant redirect as https//ratticdb 
when i open browser and hit https://ratticdb it will say unable to conncet ratticdb(problem loading page)occurs..
please help me to rectify this
In my 000-default.conf
ServerAdmin webmaster@localhost
DocumentRoot /opt/apps/RatticWeb/static/
Servername ratticdb
Redirect permanent  / https://ratticdb
