### ISSUE TITLE
Multiple Password Groups

### ISSUE THREAD

**Issue by plabbett** [tildaslash/RatticWeb#297]
From wiki documentation on RatticDB:  "We also tried to make the ACL system as simple as possible, passwords belong to a single group, and users can be in any number of groups."

This seems counter-intuitive when using LDAP. For example, let's say I have "CustomerService" and "InformationTechnology" LDAP groups. If there is a password that I want both groups to have the same access to, I can either create duplicate password records (1 for each group I want to have access to) or I can create new LDAP groups that encompass both groups. 

Duplicating passwords across multiple groups is not a great solution because if I update it once, I have to remember to run through each instance assigned to other departments and update it.Strong potential for out of sync passwords. 

Making LDAP groups works, but depending on the complexity of the roles (groups) in AD, it can result in groups like "CustomerServiceLevel1_And_ITLevel1_And_SalesLevelI." Just as an aside, I have somewhere around 15 "roles" that each have 4 "levels." This architecture makes it hard for me to manage shared passwords between roles/levels. 

Another possible option is to create LDAP groups based on individual passwords instead of roles, but that's the reason I'm using a password manager so that I can assign passwords to levels/roles within my organization.

Just food for thought. If there is a way to achieve what I'm trying to do that I have overlooked, please let me know! thanks!

**Comment by yvangodard** [comment]
+ 1 (exactly what I want !)

**Comment by djcross** [comment]
+1

**Comment by rayvenshire** [comment]
ipernet, will you make a pull request?

**Comment by ipernet** [comment]
Hi guys,

This change the way how Rattic has been designed and if I remind correctly this was not accepted for merging into the upstream project. However feel free to use the branch on my fork!

https://github.com/KRDS/RatticWeb/tree/viewers-groups-for-passwords

**Comment by smarthall** [comment]
@ipernet I don't remember rejecting a pull request from you. Last I heard you were still developing and testing your changes. If you think it is ready for people to use we would love you to submit a pull request to get it into RatticDB proper. Clearly there is enough demand for it.

**Comment by Jay2k1** [comment]
Can't wait for this to be merged. For me, this is a key feature without which the tool wouldn't be useful where I work at.

**Comment by smarthall** [comment]
This has now been merged to master. Thanks very much to @ipernet for putting in the hard yards to write the code. We are planning a new release of RatticDB soon, so test it out, see how it feels and let us know.
