### ISSUE TITLE
Allow users to view RatticDB in their preferred language

### ISSUE THREAD

**Issue by smarthall** [tildaslash/RatticWeb#312]
We've had a few requests for RatticDB to be easier to use in other languages, the best way to do this is to provide translations for it. We have a good start with French on our Transifex page, and a small amount done for some novelty languages. Its now time to include these with RatticDB properly.

The Transifex page can be viewed here: https://www.transifex.com/projects/p/ratticdb/

Django's Translation Guide is available here: https://docs.djangoproject.com/en/1.6/topics/i18n/translation/

**Comment by Mte90** [comment]
Uhm this feature not work, also the language switcher not work. I've tried with change all the language but i see always the page in english.

**Comment by Mte90** [comment]
![rattic1](https://cloud.githubusercontent.com/assets/403283/6643151/5b8bb270-c9aa-11e4-8894-bd4c1abc52fe.png)
problem with all the language, i've marked the string translated but is missing the rest.

**Comment by smarthall** [comment]
have you run `./manage.py compilemessages`?

**Comment by Mte90** [comment]
uh okay this command fix the problem with a restart of apache :-)

**Comment by smarthall** [comment]
I'll make sure it gets added to the documentation :wink:

**Comment by Reeslo** [comment]
Don't work for me all the text are not translated in french, I've downloaded the last .po and run "./manage.py compilemessages" but don't work, see :
![ratticdb](https://cloud.githubusercontent.com/assets/2724844/8701011/b397d05e-2b0f-11e5-99b0-d4b347d03287.png)

**Comment by Mte90** [comment]
problem confirmed with a new installation, all the language translate at every switch the same strings but not all the strings
