### ISSUE TITLE
Disabling two factor authentication bug

### ISSUE THREAD

**Issue by b18** [tildaslash/RatticWeb#325]
I can confirm that when using LDAP integration, and trying to log in as an admin to disable two factor authentication for a different user there is a bug. To recreate -

- Log in with an admin account.
- Click Staff Management.
- Click user account other than your own.
- Choose to disable two factor authentication.
- You are then taken to the URL to disable two factor authentication for your OWN account that you're logged in with, not the other users.

You can bypass this issue by changing the URL in your browser to reflect the user ID (number) of the other user, but still can be confusing when you're expecting to be disabling this for the user's page that you chose to do so from.

**Comment by Zemmiph0bia** [comment]
Hey there, 

Thanks for raising a bug with rattic, we'll try and look into it as soon as we can (Which will likely be within the next two weeks) but just to confirm, which version of rattic are you using? 

Eliza.

**Comment by b18** [comment]
No problem! You're very welcome. I'm running v1.2.2.

Let me know if you need anything else. Thanks!
