### ISSUE TITLE
Prevent browser password manager to autofill passwords on edit

### ISSUE THREAD

**Issue by andrekeller** [tildaslash/RatticWeb#327]
Hi,

when editing passwords my browser (chromium) insists on auto-filling passwords. Is there a way to prevent that?

**Comment by Zemmiph0bia** [comment]
Hey there, 
I'm not sure if this is useful but there are some auto-fill settings in chrome, but this seems very similar to an older issue we had #318. 

**TL:DR;** The amount of work required to fix this particular issue is too much for the benefit gained. 

However, we'd love to see this get fixed - if you feel up to it, we :heart: pull requests. If you want to have an attempt at this, let me know as I am more than happy to put you in the right direction. 

![screen shot 2015-02-02 at 8 04 10 pm](https://cloud.githubusercontent.com/assets/1581440/5998035/bf85500e-ab16-11e4-880b-1185ce837666.png)
