### ISSUE TITLE
Add Tag and Note to search

### ISSUE THREAD

**Issue by eltrentin** [tildaslash/RatticWeb#330]
It would be great search by Tag and Note. Now it's only possibile to search in the password "title".
The same thinkg do KeePass.

And idea is to put, in the search box, like a check box in which select "search to" title (default), tags, note, all.

**Comment by Zemmiph0bia** [comment]
Hey there! 

Thanks for using Rattic and your suggestion, I'm going to close this as we already have an issue open. 

Thanks, 
Eliza.

**Comment by xhaggi** [comment]
as a workaround to additionally search in the url and description change the following line
https://github.com/tildaslash/RatticWeb/blob/master/cred/search.py#L30
to
```
cred_list = cred_list.filter(Q(title__icontains=value) | Q(url__icontains=value) | Q(description__icontains=value))
``

**Comment by yanky83** [comment]
Bump.

Searching through all fields would be very helpful (especially URL e.g.). Should be an easy thing to do, and many would benefit from it!?

Thx in advance.
