### ISSUE TITLE
Truncated or oversized response headers received from daemon process

### ISSUE THREAD

**Issue by albundy83** [tildaslash/RatticWeb#366]
Hello,

on debian 8 jessie with apache 2.4 and libapache2-mod-wsgi 4.3.0-1, I have the following error : 
```javascript
[Thu May 28 22:12:00.749906 2015] [wsgi:error] [pid 26226:tid 140043238729472] [client XXXX:37501] Truncated or oversized response headers received from daemon process 'rattic': /usr/local/RatticWeb/ratticweb/wsgi.py
```

Here the configuration I have applied : 
```javascript
Alias /robots.txt /usr/local/RatticWeb/static/robots.txt
Alias /favicon.ico /usr/local/RatticWeb/static/favicon.ico

AliasMatch ^/([^/]*\.css) /usr/local/RatticWeb/static/styles/$1

Alias /media/ /usr/local/RatticWeb/media/
Alias /static/ /usr/local/RatticWeb/static/

<Directory /usr/local/RatticWeb/static>
  Require all granted
</Directory>

<Directory /usr/local/RatticWeb/media>
  Require all granted
</Directory>

WSGIScriptAlias / /usr/local/RatticWeb/ratticweb/wsgi.py
WSGIPassAuthorization On

WSGIDaemonProcess rattic processes=2 threads=25 home=/usr/local/RatticWeb/ python-path=/usr/local/RatticWeb display-name=%{GROUP}
#WSGIDaemonProcess rattic processes=2 threads=25 python-path=/usr/local/RatticWeb
WSGIProcessGroup rattic

<Directory /usr/local/RatticWeb/ratticweb>
  <Files wsgi.py>
    Require all granted
  </Files>
</Directory>
```

When I remove at least home or python-path directive, it works but I have some error about path or file not found ...

Please help me ;(

**Comment by albundy83** [comment]
So, I finally fix the problem, according to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=758035 the version included in debian 8 is buggy.
So, here a workaround until version is upgrade to at least mod_wsgi 4.4.10 I think, you must use the version from pip (https://pypi.python.org/pypi/mod_wsgi)
You need to install a apache2-dev package and mod_wsgi from pip : 
```bash
apt-get install apache2-dev
pip install mod_wsgi
```
Then, just replace the path of mod_wsgi.so in file /etc/apache2/mods-available/wsgi.load :

```bash
cat /etc/apache2/mods-available/wsgi.load   
#LoadModule wsgi_module /usr/lib/apache2/modules/mod_wsgi.so
LoadModule wsgi_module /usr/local/lib/python2.7/dist-packages/mod_wsgi/server/mod_wsgi-py27.so
```

Restart apache2 and check from error log that the correct new mod_wsgi has been loaded (version should be 4.4.12 for example) :
```javascript
[Mon Jun 01 11:06:13.217542 2015] [mpm_event:notice] [pid 6405:tid 139834621618048] AH00489: Apache/2.4.10 (Debian) OpenSSL/1.0.1k mod_wsgi/4.4.12 Python/2.7.9 configured -- resuming normal operations
```

You don't need to change anything else from Rattic config.

**Comment by smarthall** [comment]
Awesome! Thanks for the update! Hopefully this will help anyone else experiencing the issue.

**Comment by StephanZaat** [comment]
Agreed! This also works on Ubuntu 16.04 LTS.
