### ISSUE TITLE
Installation with a none root url does not work

### ISSUE THREAD

**Issue by tverhoeven** [tildaslash/RatticWeb#381]
I have installed RatticDB 1.3.1 on a fresh and up-to-date CentOS 7 with SELinux enabled and a PostgreSQL backend. I've followed the instructions and everything went fine. Except I need to run Rattic on a none-root alias (http://servername/password/ instead of http://servername/). I've modified all files correctly I think. But I get 404 errors when going to the URL:

Page not found (404)
Request Method: 	GET
Request URL: 	http://<server-ip>/password/

Using the URLconf defined in ratticweb.urls, Django tried these URL patterns, in this order:

    ^password/
    ^password\/static\/(?P<path>.*)$ 

The current URL, , didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

This is my local.cfg:

[ratticweb]
debug = False
#debug = True
secretkey = <my key>
hostname = <ip-of-server>
timezone = Europe/Brussels
urlroot = /password/

[filepaths]
static = /var/www/html/password/static

[database]
engine = django.db.backends.postgresql_psycopg2
name = rattic
user = <db username>
password = <db password>
host = 127.0.0.1
port = 5432

[email]
from_email = <our default system email address>

And this is my rattic.conf part of the apache config:

Alias /password/robots.txt /var/www/html/password/static/robots.txt
Alias /password/favicon.ico /var/www/html/password/static/favicon.ico
AliasMatch ^/password/([^/]*\.css) /var/www/html/password/static/styles/$1
Alias /password/media/ /var/www/html/password/media/
Alias /password/static/ /var/www/html/password/static/

<Directory /var/www/html/password/static>
    #Order deny,allow
    #Allow from all
    Require all granted
</Directory>

<Directory /var/www/html/password/media>
    #Order deny,allow
    #Allow from all
    Require all granted
</Directory>

#WSGISocketPrefix run/wsgi
WSGIScriptAlias /password/ /var/www/html/password/ratticweb/wsgi.py
WSGIPassAuthorization On
WSGIDaemonProcess rattic processes=2 threads=25 home=/var/www/html/password/ python-path=/var/www/html/password display-name=%{GROUP}
WSGIProcessGroup rattic

<Directory /var/www/html/password/ratticweb>
    <Files wsgi.py>
        #Order deny,allow
        #Allow from all
        Require all granted
    </Files>
</Directory>

**Comment by ak4t0sh** [comment]
In your apache config try to replace ```WSGIScriptAlias /password/ /var/www/html/password/ratticweb/wsgi.py``` by ``WSGIScriptAlias / /var/www/html/password/ratticweb/wsgi.py```
Worked for me ;)

**Comment by tverhoeven** [comment]
Ok, that solved it. Strange, because I thought that I tested that combination.

Thanks for the help,
Tim
