### ISSUE TITLE
Apache setup

### ISSUE THREAD

**Issue by Goatmaster** [tildaslash/RatticWeb#383]
Hey,
I have installed everything like in the guide. https://github.com/tildaslash/RatticWeb/wiki/installing

But I don't understand where exactly I have to put this: 
Alias /robots.txt /opt/apps/RatticWeb/static/robots.txt
Alias /favicon.ico /opt/apps/RatticWeb/static/favicon.ico

AliasMatch ^/([^/]*\.css) /opt/apps/RatticWeb/static/styles/$1

Alias /media/ /opt/apps/RatticWeb/media/
Alias /static/ /opt/apps/RatticWeb/static/

<Directory /opt/apps/RatticWeb/static>
Order deny,allow
Allow from all
</Directory>

<Directory /opt/apps/RatticWeb/media>
Order deny,allow
Allow from all
</Directory>

WSGIScriptAlias / /opt/apps/RatticWeb/ratticweb/wsgi.py
WSGIPassAuthorization On

WSGIDaemonProcess rattic processes=2 threads=25 home=/opt/apps/RatticWeb/ python-path=/opt/apps/RatticWeb display-name=%{GROUP}
WSGIProcessGroup rattic

<Directory /opt/apps/RatticWeb/ratticweb>
  <Files wsgi.py>
    Order deny,allow
    Allow from all
  </Files>
</Directory>

What is the path of the file? The redirect to ssl works fine.

**Comment by ak4t0sh** [comment]
__apache 2.2__
1. Create the file /etc/apache2/conf.d/rattic.conf and paste it your configuration 
2. Reload apache

__apache 2.4__
1. Create the file /etc/apache2/conf-available/rattic.conf and paste it your configuration.
2. Enable the new conf (a2enconf rattic)
3. Reload apache

**Comment by Goatmaster** [comment]
Okay I have apache 2.4 so I have done it. But if I open htttp://localhost it redirects me to https://localhost. But it still shows the Apache Default Page.

**Comment by ak4t0sh** [comment]
Could you paste your apache config (vhost included)  ?
Use markdown to format it in more readable way ;)

**Comment by ak4t0sh** [comment]
By the way as you are using Apache 2.4 replace all 
```ApacheConf
Order deny,allow
Allow from all
```
by 
```ApacheConf
Require all granted
```

;)

**Comment by Goatmaster** [comment]
Now a I get a forbidden error, but it shows the favicon from rattic.

**Comment by ak4t0sh** [comment]
Could you paste your apache config (rattic config + vhost) ?

**Comment by Goatmaster** [comment]
/etc/apache2/sites-enabled/000-default.conf

```
NameVirtualHost *:80
<VirtualHost *:80>
   ServerName localhost
   ServerAlias localhost
   Redirect permanent / https://localhost/
</VirtualHost>
```

/etc/apache2/conf-available/rattic.conf

```
Alias /robots.txt /opt/apps/RatticWeb/static/robots.txt
Alias /favicon.ico /opt/apps/RatticWeb/static/favicon.ico

AliasMatch ^/([^/]*\.css) /opt/apps/RatticWeb/static/styles/$1

Alias /media/ /opt/apps/RatticWeb/media/
Alias /static/ /opt/apps/RatticWeb/static/

<Directory /opt/apps/RatticWeb/static>
Require all granted
</Directory>

<Directory /opt/apps/RatticWeb/media>
Require all granted
</Directory>

WSGIScriptAlias / /opt/apps/RatticWeb/ratticweb/wsgi.py
WSGIPassAuthorization On

WSGIDaemonProcess rattic processes=2 threads=25 home=/opt/apps/RatticWeb/ pytho$
WSGIProcessGroup rattic


<Directory /opt/apps/RatticWeb/ratticweb>
  <Files wsgi.py>
    Order deny,allow
    Allow from all
  </Files>
</Directory>
```

**Comment by ak4t0sh** [comment]
Try to replace 

``` ApacheConf
<Files wsgi.py>
    Order deny,allow
    Allow from all
</Files>
```

by

``` ApacheConf
<Files wsgi.py>
    Require all granted
</Files>
```

and reload apache

**Comment by Goatmaster** [comment]
internal it works now, but if I try to connect it from another device in the network with the ip I get an "Bad Request (400)" error.

**Comment by ak4t0sh** [comment]
Could you paste your vhost for https ?
Moreover to allow external access you have to replace 

``` ApacheConf
Redirect permanent / https://localhost/
```

By

``` ApacheConf
Redirect permanent / https://MY.PUBLIC.HOSTNAME.OR.PUBLIC.IP/
```

**Comment by Goatmaster** [comment]
It happens the same if I try to load https://"hostip"/

**Comment by Goatmaster** [comment]
Seems like a Apache problem, I will try to fix it by myself. Thank you for your help!
