### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Goatmaster** [tildaslash/RatticWeb#404]
Are you still working on the project, do you plan to release a new version in the next time?

**Comment by smarthall** [comment]
We aren't dead, both @Zemmiph0bia and myself have full time jobs. Sometimes we don't get as much time as we would like to work on RatticDB.

RatticDB has hit the point where it is getting a little difficult to maintain and we are currently exploring plans to rebuild it. As part of a rebuild we are also investigating making it easier to package for distribution owners and easier to install for sysadmins. Finally since we are considering a complete rebuild we are also investigating implementing host proof encryption.

Anyway stay tuned to our mailing list for details once we narrow down the path we want to go in.

**Comment by drts01** [comment]
I am looking for alternatives for LastPass and this looks very interesting. I have only just become aware of this project and have not been on the mailing list. Why have we not heard anything in so long? Does the project need funding? developers? unable to come to consensus? Without at least some communications on the site, blog, twitter, etc, I am extremely hesitant to suggest this to my team.

Thanks for your work thus far and I hope it continues.

**Comment by ak4t0sh** [comment]
Few month ago Eliza mailed me they planning to release Rattic 2.0 but when i asked for a roadmap to see what i could do to help i had no answer...To bad this project seemed promising.

**Comment by PacketPerception** [comment]
Looks pretty dead...

**Comment by lhoss** [comment]
Indeed a real pity!

It would be nice to know  what you people here  decided
- opted for it, even forking it,  customizing it?
- opted for a diff project?  open-source?  or a web-service like offered by LastPass?

The best other open-source project I found (I will evaluate today):  http://teampass.net

ps: I checked out the github forks, but did not find a very active one. Following has quite some extra commits , but last one only Dec. 2015: https://github.com/danislav/RatticWeb

**Comment by mitietoni** [comment]
Hi [lhoss ](https://github.com/lhoss), I did try teampass but after a lot of bugs founded I leaved it and go for ratticdb.
Of course the think that ratticdb is dead is bad, I hope they give us some news soon.

**Comment by PacketPerception** [comment]
I'm looking into https://vaultproject.io atm. I'm going to try building up a quick prototype web-ui for it this weekend to see if it will fit my needs.

**Comment by mitietoni** [comment]
So, we wait good news :-) The best will be also with a syncronization tools for the various os.
At time, I chose ratticdb because it have also a good mobile web interface

**Comment by drts01** [comment]
@lhoss Teampass is what I was considering too. What do you think so far?
@djzippo the UI is a big reason why I wanted to evaluate Rattic.
@PacketPerception a password manager with Vault as a backend sounds very interesting. I would love to hear about your experience.

**Comment by jeremyrp** [comment]
@PacketPerception I think it's a great idea to layer a BUI on top of Vault.  I've been evaluating Vault for both key mgmt and secrets sharing on a project, with very promising results so far.  I would gladly get behind a project for a BUI and provide what assistance I could.

**Comment by lhoss** [comment]
@CMeza99 just fyi , I tried the 1. of following Teampass docker containers:
- http://www.appcontainers.com/teampass/
- https://bitbucket.org/thiagofanfoni/teampass
- https://github.com/jcherqui/docker-teampass (4*)

That ran with a bit outdated Teampass v1.24. 
It working out-of-the-box (with 'standalone' mode, meaning that mysql ran locally in the same docker container) .. but finally rethought our strategy and opted to give the more professional lastpass (enterprise) a chance!

**Comment by ak4t0sh** [comment]
Just found https://github.com/passbolt/passbolt via @Mte90 profile. it seems to be a good alternative. Does somebody have feedback on it ? I think i'm going to try it when i'll have free time

**Comment by Mte90** [comment]
I abandoned ratticweb after also my pr rejected.
I tried teampass but the ui/ux is the worst that i can see for a software and passbolt i think that is very interesting but actually i cannot try (i don't have a vps for that).

**Comment by mitietoni** [comment]
@ak4t0sh Passbolt seems interesting but how can I login from mobile? For this moment it is compatible only with firefox on pc. Security without access is not the best thing. Access with double authentication of ratticdb is the best for me.
@Mte90 contact me if you need vps.

**Comment by Eh1k0** [comment]
So completely dead?

**Comment by PacketPerception** [comment]
check out https://github.com/keeweb/keeweb
not entirely the same, but better than nothing

**Comment by Goatmaster** [comment]
We are using this for a while now and we are satisfied with it.
[https://github.com/nuxsmin/sysPass]

**Comment by gionniboy** [comment]
hi guys

i'm talking in this day with other people: we want fork the project.

We are studying the apps and we planning a migration to django 1.11 for the end of december 2016 and start the new fork with a big update and so on.

Do you like the idea? Do you want join the project? We are setting up some tools to collaborate better...

if you like the idea tell me.

**Comment by RasmusEdgar** [comment]
@gionniboy 

I want to join the project.

Br
