### ISSUE TITLE
SOUTH DATABASE ADAPTERS

### ISSUE THREAD

**Issue by ghost** [tildaslash/RatticWeb#441]
Hello, 

I'm having an issue with RatticDB install and giving always this error:

There is no South database module 'south.db.mysql' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

This happens when I try to run: 
# ./manage.py syncdb --noinput

I tried to uninstall south, and then have error importing the module, then install it again and the error above.

Can you help me figuring this out?

Thanks.

**Comment by jwmarshall** [comment]
See this thread:

https://github.com/tildaslash/RatticWeb/issues/405

**Comment by ghost** [comment]
@jwmarshall thank you very much for your help.

It solved my problem.

Now I have this information on my personal notes ;)

**Comment by jwmarshall** [comment]
Will hopefully provide a PR with fixes today.
